providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gcc", "freetds", "wget"]

[phases.download_models]
dependsOn = ["setup"]
cmds = [
  "mkdir -p app/onnx",
  "wget -O app/onnx/model.onnx https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.int8.onnx",
  "wget -O app/voices.bin https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin"
]

[phases.install]
dependsOn = ["download_models"]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && python -m ensurepip --upgrade",
  ". /opt/venv/bin/activate && pip install -r app/requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
