providers = ["python"]

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y curl gnupg2 unixodbc-dev",
  "curl -sSL -O https://packages.microsoft.com/config/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '\"' -f 2)/packages-microsoft-prod.deb",
  "dpkg -i packages-microsoft-prod.deb",
  "rm -f packages-microsoft-prod.deb",
  "apt-get update",
  "ACCEPT_EULA=Y apt-get install -y msodbcsql18"
]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r app/requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
